### PR TITLE
revise applyPatchTemplateHaskellLanguageHaskellTHSyntax

### PR DESCRIPTION
**Pull request by shayne-fletcher**
(1) 4aea0a72040e862ab518d911057905e8cf8d15fb makes changes to `ghc/libraries/template-haskell/Language/Haskell/TH/Syntax.hs` so that the patch we introduced recently no longer applies. switch to manually patching it.

(2) 432c736c19446a011fca1f9485c67761c991bd42 made more changes to `GHC/Driver/Make.hs` (sigh).

(3) last two days, `git clone https://gitlab.haskell.org/ghc.git` has been failing the windows CI builds
```
Cloning into 'ghc'...
error: RPC failed; curl 56 HTTP/2 stream 5 was reset
fatal: expected 'packfile'
```
this can be worked around by switching to `git clone https://github.com/ghc/ghc.git` so do this in the windows case.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da @dylant-da @akrmn

**Comment by garyverhaegen-da** [comment]
> sweet! thanks @garyverhaegen-da. ok to land please?

That's a bit too much for me to review but I'll reach out to smarter people internally.

**Comment by basvangijzel-DA** [comment]
Moisés and Dylan are at Zurihac, and should be available to review from Wednesday. Thanks for all the work @shayne-fletcher!

**Review by akrmn — APPROVED** [review]
LGTM, thanks @shayne-fletcher

**Pull request merged**
