### PR TITLE
Refactor calc modules

### PR DESCRIPTION
**Pull request by shayne-fletcher**
refactor `calcParserModues` and `libParserModules`

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
@samuel-williams-da @dylant-da

**Comment by dylant-da** [comment]
Taking a look now

**Comment by shayne-fletcher** [comment]
> Taking a look now

any updates?

**Review by dylant-da — APPROVED** [review]
Looks great, definitely clears things up

**Comment by dylant-da** [comment]
> > Taking a look now
> 
> any updates?

Sorry, I got a bit sidetracked

**Comment by shayne-fletcher** [comment]
> > > Taking a look now
> > 
> > 
> > any updates?
> 
> Sorry, I got a bit sidetracked

no worries @dylant-da . thanks for landing it!

**Pull request merged**
