### PR TITLE
Disable optimization for specific source files

### PR DESCRIPTION
**Pull request by shayne-fletcher-da**
Disable optimizations selectively for `DynFlags.hs` and `HsInstances.hs` to reduce (user) compile times. See the discussion at https://github.com/digital-asset/ghc-lib/issues/39 for more details.

### CODE REVIEW

**Comment by ndmitchell** [comment]
What's the time difference?

**Comment by shayne-fletcher-da** [comment]
> What's the time difference?

See https://github.com/digital-asset/ghc-lib/issues/39

**Comment by cocreature** [comment]
Have you benchmarked how big the performance hit on the runtime of `damlc` on large projects is?

**Comment by shayne-fletcher-da** [comment]
> Have you benchmarked how big the performance hit on the runtime of `damlc` on large projects is?

No. See https://github.com/digital-asset/ghc-lib/issues/39 however where it is suggested that it is not expected to "have a measurable impact".

**Comment by cocreature** [comment]
I would still like to see specific numbers for `damlc build` on a large project before we merge this. I wouldn’t be surprised if we end up using the GHC API in a slightly different way then GHC itself so even if the impact on GHC might be small, the impact on `damlc` could be significant.

**Comment by shayne-fletcher-da** [comment]
I've produced the means to make comparisons.
```
Comparison of branches:
  - master
  - ghc-lib-8.8.0.20190704-selective-optimizations-off
  - ghc-lib-8.8.0.20190704.1-all-optimizations-off
Build times verified consistent with expectations (e.g. the last one is fast).
Results for
 `time bazel run //daml-foundations/daml-ghc:daml-ghc-test-dev -- --pattern=`
(last col. is mean):

8.8.0.20190612                             | 31.710s 30.102s 30.021s 29.616s | 30.362s
8.8.0.20190704-selective-optimizations-off | 30.876s 32.406s 32.252s 31.486s | 31.755s
8.8.0.20190704.1-all-optimizations-off     | 36.939s 35.454s 36.021s 35.269s | 35.921s
```
@cocreature can you provide instructions for a more convincing test?

**Comment by shayne-fletcher-da** [comment]
Turning off optimizations basically doubles the execution time.
```
Results for Spider `time daml build`:
8.8.0.20190612                             | 3m25.391s 3m25.164s | 3m25.28
8.8.0.20190704-selective-optimizations-off | 3m17.858s 3m17.276s | 3m17.56
8.8.0.20190704.1-all-optimizations-off     | 5m48.609s 5m47.950s | 5m47.30
```

**Comment by shayne-fletcher-da** [comment]
```
* 8.8.0.20190612

LSP
  diagnostics
    diagnostics disappear after error is fixed:    OK (1.22s)
    diagnostics appear after introducing an error: OK (1.07s)
    percent encoding does not matter:              OK (1.06s)
    failed name resolution:                        OK (1.08s)
    import cycle:                                  OK (0.39s)
    import error:                                  OK (0.39s)
    multi module funny:                            OK (1.09s)
    parse error:                                   OK (1.09s)
    type error:                                    OK (1.10s)
    scenario error:                                OK (3.60s)
  requests
    code-lenses:                                   OK (1.26s)
    type on hover: name:                           OK (0.43s)
    type on hover: literal:                        OK (0.41s)
    definition:                                    OK (0.44s)
  scenarios
    opening codelens produces a notification:      OK (3.12s)
    scenario ok:                                   OK (3.13s)
    spaces in path:                                OK (3.48s)
  Stress tests
    Modify a file 2000 times:                      OK (5.08s)
    Set 10 files of interest:                      OK (1.34s)
    Type check 100-deep module chain:              OK (1.78s)

All 20 tests passed (32.55s)

* 8.8.0.20190704-selective-optimizations-off

LSP
  diagnostics
    diagnostics disappear after error is fixed:    OK (1.73s)
    diagnostics appear after introducing an error: OK (1.19s)
    percent encoding does not matter:              OK (1.17s)
    failed name resolution:                        OK (1.18s)
    import cycle:                                  OK (0.43s)
    import error:                                  OK (0.42s)
    multi module funny:                            OK (1.15s)
    parse error:                                   OK (1.15s)
    type error:                                    OK (1.38s)
    scenario error:                                OK (3.48s)
  requests
    code-lenses:                                   OK (1.31s)
    type on hover: name:                           OK (0.48s)
    type on hover: literal:                        OK (0.45s)
    definition:                                    OK (0.56s)
  scenarios
    opening codelens produces a notification:      OK (2.29s)
    scenario ok:                                   OK (3.44s)
    spaces in path:                                OK (3.35s)
  Stress tests
    Modify a file 2000 times:                      OK (4.93s)
    Set 10 files of interest:                      OK (1.37s)
    Type check 100-deep module chain:              OK (1.85s)

All 20 tests passed (33.29s)

* 8.8.0.20190704.1-all-optimizations-off

LSP
  diagnostics
    diagnostics disappear after error is fixed:    OK (1.31s)
    diagnostics appear after introducing an error: OK (1.18s)
    percent encoding does not matter:              OK (1.17s)
    failed name resolution:                        OK (1.15s)
    import cycle:                                  OK (0.41s)
    import error:                                  OK (0.42s)
    multi module funny:                            OK (1.19s)
    parse error:                                   OK (1.16s)
    type error:                                    OK (1.19s)
    scenario error:                                OK (3.67s)
  requests
    code-lenses:                                   OK (1.31s)
    type on hover: name:                           OK (0.65s)
    type on hover: literal:                        OK (0.50s)
    definition:                                    OK (0.69s)
  scenarios
    opening codelens produces a notification:      OK (2.18s)
    scenario ok:                                   OK (3.21s)
    spaces in path:                                OK (3.34s)
  Stress tests
    Modify a file 2000 times:                      OK (7.11s)
    Set 10 files of interest:                      OK (1.50s)
    Type check 100-deep module chain:              OK (2.28s)

All 20 tests passed (35.61s)
```

**Pull request merged**
