### PR TITLE
Format with ormolu

### PR DESCRIPTION
**Pull request by shayne-fletcher**
prefer `join` over `++` and format with ormolu.

### CODE REVIEW

**Comment by samuel-williams-da** [comment]
Could we have this checked in CI/precommit of some kind?

**Comment by samuel-williams-da** [comment]
Also, why the preference of `join` over `++` or `<>`?

**Comment by shayne-fletcher** [comment]
> Could we have this checked in CI/precommit of some kind?

it sounds like a good idea! i'm not quite sure what you mean. could you elaborate?

**Comment by shayne-fletcher** [comment]
> Also, why the preference of `join` over `++` or `<>`, at least in cases with only 2 lists?

ah! the end goal was to format with ormolu but they way it rendered (longer lists) with `++` just looked so terrible (to me) so i resolved to use `join` before applying it. i'm not opposed to `++` in general. i think the convention for `join` is working well here; if you see `++` now it's in the interior of a list, not top-level. i just blanket replaced the `++`s so didn't distinguish between short or long lists.

**Comment by shayne-fletcher** [comment]
> Could we have this checked in CI/precommit of some kind?

maybe you mean, a CI job that builds ghc-lib from the current GHC HEAD commit? we can do that. it's implemented as `cabal run exe:ghc-lib-build-tool -- --ghc-flavor ""`

**Comment by paulbrauner-da** [comment]
> > Could we have this checked in CI/precommit of some kind?
> 
> it sounds like a good idea! i'm not quite sure what you mean. could you elaborate?

Hi Shayne. I think what @samuel-williams-da means is we could have a pre-commit hook that runs the formatter, and we could have a CI tasks that fails if the code is not formatted.

**Comment by samuel-williams-da** [comment]
Paul is correct, it should be relatively easy to add as a job.
Regarding `join`, I see ormolu does make it kind of ugly, I don't mind either way

**Comment by shayne-fletcher** [comment]
> Paul is correct, it should be relatively easy to add as a job. 

yes, it's easy. similarly we should reintroduce hlint. can these things be done in a later PR though please?

**Comment by samuel-williams-da** [comment]
Sure I'm okay with that

**Pull request merged**
