### PR TITLE
Update README; build compiler min version info

### PR DESCRIPTION
**Pull request by shayne-fletcher**
- Sync to https://gitlab.haskell.org/ghc/ghc.git @ `545cfefaa88b31daa2cb3519b7561171e7ca51b3`;
- Update README
  - Note that you need >= ghc-8.8.1 to build ghc-lib-parser-9.*
    - See discussion in https://github.com/digital-asset/ghc-lib/issues/282

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Thanks!

**Comment by cocreature** [comment]
this has conflicts that need resolving

**Comment by shayne-fletcher** [comment]
> this has conflicts that need resolving

goodness. i am at a loss to explain how that happened or why i can't get a local conflict? anyway, resolved.

**Comment by shayne-fletcher** [comment]
oh i see. this is an old PR :) yes, ok, things have moved on since this was raised. makes sense now.

**Comment by cocreature** [comment]
> oh i see. this is an old PR :) yes, ok, things have moved on since this was raised. makes sense now.

sorry not sure how I missed this for so long.

**Comment by shayne-fletcher** [comment]
> > oh i see. this is an old PR :) yes, ok, things have moved on since this was raised. makes sense now.
> 
> sorry not sure how I missed this for so long.

don't worry 'bout it! woulda pinged you if it were an important one 😄

**Pull request merged**
