### PR TITLE
scope exceptions patch

### PR DESCRIPTION
**Pull request by shayne-fletcher**
exceptions is depended on by flavors >= 9.0. it's shipped with the compiler from the 8.10 series onwards so the patch is only necessary when it's possible the build compiler is in the 8.8 series or in other words, `ghcSeries ghcFlavor == Ghc90` so don't apply it unnecessarily.

two key tests:
(1) 9.0.2/8.8.4
  - `stack runhaskell --stack-yaml stack.yaml --resolver lts-16.31 --package extra --package optparse-applicative CI.hs -- --ghc-flavor ghc-9.0.2 --stack-yaml stack.yaml --resolver lts-16.31 `
  
(2) 9.2.7/8.10.7
  - `stack runhaskell --stack-yaml stack.yaml --resolver lts-18.28 --package extra --package optparse-applicative CI.hs -- --ghc-flavor ghc-9.2.7 --stack-yaml stack.yaml --resolver lts-18.28`

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
cc @moisesackerman-da @garyverhaegen-da @dylant-da

**Comment by shayne-fletcher** [comment]
cc @moisesackerman-da @dylant-da @garyverhaegen-da ping 😄

**Review by akrmn — APPROVED** [review]
LGTM, thanks @shayne-fletcher!

**Pull request merged**
