### PR TITLE
Combine ghc-8.8.1 and da-ghc-8.8.1

### PR DESCRIPTION
**Pull request by cocreature**
This is a first step towards merging all branches so we don’t have to
spend time trying to keep them in sync.

For now, this only merges ghc-8.8.1 and da-ghc-8.8.1. I’ll leave
master for a separate PR.

### CODE REVIEW

**Comment by cocreature** [comment]
I would like to see CI run on this before we merge this so we should merge #122 first (Apparently I don’t have the permissions to manually queue builds on ghc-lib).

**Comment by garyverhaegen-da** [comment]
Seems to be something fishy going on on GitHub's side:
```
# Running: cd ghc && git remote add upstream git@github.com:digital-asset/ghc.git
# Completed in 0.01s: cd ghc && git remote add upstream git@github.com:digital-asset/ghc.git



# Running: cd ghc && git fetch upstream
Host key verification failed.
```

That normally means the host key from `github.com` has changed since it was last added to `~/.ssh/known_hosts`. 🤔

**Comment by cocreature** [comment]
We can probably just use the https URL for cloning instead.

**Comment by cocreature** [comment]
CI still doesn’t seem to be running :confused:

**Comment by cocreature** [comment]
Actually I’m now confused how the config file works at all. Does Azure always assume that the one in master is the one that matters or how does it figure out which branch it needs to look at?

**Comment by garyverhaegen-da** [comment]
That is something we manually set up in Azure when creating the pipeline; this one is indeed set to look at the master branch. I suspect this is not running because it's not rebased on master, so master as seen from here doesn't include #122 yet.

**Comment by cocreature** [comment]
Hm, but I don’t actually want to rebase this on master since that includes other changes that this branch is not yet ready for.

**Comment by garyverhaegen-da** [comment]
I've queued the build for now, but I don't think you'll get automated builds here until `da-ghc-8.8.1` is a descendant of `master`. I could be wrong, though.

**Comment by cocreature** [comment]
Alright, I was planning to tackle merging master into this as the next step so it’s not too much of an issue if you don’t mind me bugging you about this PR a few times.

**Comment by garyverhaegen-da** [comment]
Well, it's not failing one step further, so, "progress", I suppose.

```
# Running: cd ghc && git fetch upstream
From https://github.com/digital-asset/ghc
 * [new branch]            da-master         -> upstream/da-master
 * [new branch]            da-master-8.8.1   -> upstream/da-master-8.8.1
 * [new branch]            da-unit-ids       -> upstream/da-unit-ids
 * [new branch]            da-unit-ids-8.8.1 -> upstream/da-unit-ids-8.8.1
 * [new branch]            master            -> upstream/master
 * [new branch]            print_fun_binds   -> upstream/print_fun_binds
# Completed in 1.58s: cd ghc && git fetch upstream



# Running: cd ghc && git merge --no-edit upstream/da-master-8.8.1 upstream/da-unit-ids-8.8.1

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <vsts@fv-az644.qvrbacwriqqevjttc1tozqvw0c.bx.internal.cloudapp.net>) not allowed
```

You can override those inline with
```
git -c "user.name="Doesn't matter" -c "user.email="doesnt.matter@example.com" merge --no-edit upstream/da-master-8.8.1 upstream/da-unit-ids-8.8.1
```

**Comment by cocreature** [comment]
Thanks, I’ve tried to change it.

**Comment by cocreature** [comment]
ugh, I put `-c` after `merge` which broke. If you temporarily give me permissions to queue builds, you might save yourself some work :slightly_smiling_face:

**Comment by garyverhaegen-da** [comment]
Failed; I should have looked closer before running: the `-c` options are options to `git`, not to `git-merge` (which is a different executable called by `git merge`) so they need to be between `git` and `merge`.

**Comment by garyverhaegen-da** [comment]
Ah well. Was worth a try.

**Comment by garyverhaegen-da** [comment]
The `git` stuff seems to be fine, but now this:
```
# Running: stack exec --no-terminal -- mini-hlint examples/mini-hlint/test/MiniHlintTest.hs
Cabal file warning in/home/vsts/work/1/s/examples/mini-compile/mini-compile.cabal@0:0: Boolean values are case sensitive, use 'True' or 'False'.
Cabal file warning in/home/vsts/work/1/s/examples/mini-compile/mini-compile.cabal@0:0: Boolean values are case sensitive, use 'True' or 'False'.
/home/vsts/work/1/s/.stack-work/install/x86_64-linux/df87cdf477ab77add923b805dbc02cdbc10ec7cef2aad8f0f7151e038e8e0f3a/8.4.3/bin/mini-hlint: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
CI.hs: Failed when running system command: stack exec --no-terminal -- mini-hlint examples/mini-hlint/test/MiniHlintTest.hs
CallStack (from HasCallStack):
  error, called at src/System/Process/Extra.hs:34:9 in extra-1.6.9-AT5lAJP3xwQ1W64AcsUUkC:System.Process.Extra
  system_, called at CI.hs:189:30 in main:Main
```
I'm afraid I don't have any useful suggestion here.

**Comment by cocreature** [comment]
I think it might be the most reasonable option to just remove that hack here completely and instead patch the cabal file in the `daml` repo. We don’t really need to link against `libffi` (and we already have to patch out that hack on WIndows), we only need `libffi` headers. Adding `libffi` to `extra-libraries` makes sure that Hazel adds the headers to the Bazel sandbox. What do you think @shayne-fletcher-da?

**Comment by cocreature** [comment]
Pushed a removal of the `extra-libraries` hack so we can at least test if that’s the only issue.

**Comment by cocreature** [comment]
I believe https://github.com/digital-asset/daml/pull/2703 might allow us to get rid of the `libffi` hack completely.

**Comment by cocreature** [comment]
Merging as https://github.com/digital-asset/daml/pull/2703 has successfully build ghc-lib

**Pull request merged**
