### PR TITLE
ghc-9.6.4

### PR DESCRIPTION
**Pull request by shayne-fletcher**
ghc-9.6.4 released 2024-01-09.

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]
As always, thank you for your diligence in keeping this project up-to-date. Also, happy new year @shayne-fletcher !

**Comment by shayne-fletcher** [comment]
> Also, happy new year @shayne-fletcher !

Happy New Year @garyverhaegen-da !

**Comment by shayne-fletcher** [comment]
> the sudden failures are unexpected. sorry about that. let me look into it.

well, it seems to me that it's infra failure and whether it occurs or not is random.

testing of [this diff](https://github.com/shayne-fletcher/ghc-lib/pull/223) appears to demonstrate that switching to the newer image macOS-13 appears to overcome the issue so i've done that. let's give it another /azp run please @garyverhaegen-da

**Comment by garyverhaegen-da** [comment]
I agree it looks like an infra issue, but unfortunately it looks like switching to macos-13 didn't solve it :-(.

Not sure what else to do about it.

**Comment by shayne-fletcher** [comment]
> I agree it looks like an infra issue, but unfortunately it looks like switching to macos-13 didn't solve it :-(.
> 
> Not sure what else to do about it.

@garyverhaegen-da have pushed another commit. please /azp run one more time? i'll write up the details of what i believe the issues are while it runs.

**Comment by shayne-fletcher** [comment]
autoconf 2.72 was released fri, 22 dec 2023 [^1]. brew reports 2.72 as the current version of autoconf [^2].

using autoconf-2.72, azure with image "macOS-latest" (Big Sur [^3]) `AC_PROG_CXX` on azure/macOS appears to set `CXX` to `/usr/bin/g++ -std=gnu++11`.

in 'm4/fp_find_cxx_lib.m4' the code `"$CXX" -E actest.cpp -o actest.out` results in error `no such file or directory: /usr/bin/g++ -std=gnu++11`. if we instead we write `eval "$CXX" -E actest.cpp -o actest.out` it works the way we want.

the most recent commit then patches `if ! "$CXX" ... ` to `if ! eval "$CXX" ...` throughout 'm4/fp_find_cxx_lib.m4'. i'll raise an issue upstream.

[^1]: https://lists.gnu.org/archive/html/info-gnu/2023-12/msg00002.html
[^2]: https://formulae.brew.sh/formula/autoconf
[^3]: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

**Comment by shayne-fletcher** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/24324

**Comment by garyverhaegen-da** [comment]
Ah, that makes sense. Thanks for taking the time to detail this.

**Comment by shayne-fletcher** [comment]
MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11887

**Pull request merged**
