### PR TITLE
upgrade cabal specification: 2.0

### PR DESCRIPTION
**Pull request by shayne-fletcher**
hackage package uploads seem to have been made stricter in enforcing `cabal check` pass. so, this PR makes `ghc-lib-parser` and `ghc-lib` cabal 2.0 specification conformant.

### CODE REVIEW

**Review by akrmn — APPROVED** [review]
Looks good to me, thank you!

**Comment by shayne-fletcher** [comment]
hi @akrmn the windows failures indicate failing infra[*]. that's a shame but not related to this PR. i suggest proceeding to merge regardless. 

[*] i don't have a windows box to drill into this but in short, `stack exec pacman -S autoconf automake-wrapper make patch python tar mintty --noconfirm` has started to fail. this is a stack/ghc issue.

**Comment by shayne-fletcher** [comment]
i raised an issue for the pacman failures: https://github.com/commercialhaskell/stack/issues/5732

**Comment by shayne-fletcher** [comment]
@sofiafaro-da @akrmn can we get this attended to please?

**Pull request closed without merging**
