### PR TITLE
patch out semaphore-compat

### PR DESCRIPTION
**Pull request by shayne-fletcher**
implementation of the ghc job server protocol in [this commit](https://gitlab.haskell.org/ghc/ghc/-/commit/5c8731244bc13a3d813d2a4d53b3188b28dc8355) breaks a lot of ghc-lib builds.

for the time being, to not break those ghc-flavor ghc-9.8 builds, we need to avoid ghc-lib depending on the newly created library semaphore-compat. this PR implements a patch that does that.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
thanks @garyverhaegen-da @moisesackerman-da

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da @moisesackerman-da ... just a pinging 😅 !

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da @moisesackerman-da ... just a pinging 😅 !

Sorry for the silence; this is a bit outside my wheelhouse so I'm working on getting someone more qualified to take a look.

**Comment by shayne-fletcher** [comment]
> > @garyverhaegen-da @moisesackerman-da ... just a pinging 😅 !
> 
> Sorry for the silence; this is a bit outside my wheelhouse so I'm working on getting someone more qualified to take a look.

got it. if you need more info from me about why i think the patch is the right way to go here let me know!

**Review by akrmn — APPROVED** [review]
@shayne-fletcher thank you for this fix! sorry i didn't approve sooner, i'm just back from holidays and saw this PR now

**Comment by shayne-fletcher** [comment]
> @shayne-fletcher thank you for this fix! sorry i didn't approve sooner, i'm just back from holidays and saw this PR now

no worries, welcome back! holidays... oh yes, i remember these! 😂

**Review by dylant-da — APPROVED** [review]
Looks to good to me too :)

**Comment by shayne-fletcher** [comment]
> Looks to good to me too :)

somebody (that's not me) needs to hit the merge button 😂

**Pull request merged**
