### PR TITLE
ghcversion.h now generated by ./configure

### PR DESCRIPTION
**Pull request by shayne-fletcher**
in this sync with head `ghcversion.h` is generated now by `./configure` (was hadrian) and is moved to `rts/include`.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Nice, thank you!

**Comment by shayne-fletcher** [comment]
@cocreature looking good. ok for landing?

**Comment by shayne-fletcher** [comment]
@cocreature gentle reminder ☺️

**Pull request merged**
