### PR TITLE
less stack more cabal

### PR DESCRIPTION
**Pull request by shayne-fletcher**
this PR removes any and all uses of stack in this project. it is replaced completely by ghcup and cabal. there's a bit of cleanup work that will follow but the key objective of removing stack is done.

### CODE REVIEW

**Comment by basvangijzel-DA** [comment]
Hey Shayne, thank you for the patience, we had some big deadlines last week!

**Comment by paulbrauner-da** [comment]
Thanks Shayne! I have two questions:
- Would you mind summarizing the changes you made to the azure config outside of the stack->cabal migration? In particular, cases like `8.8.1-8.8.1` seem to have disappeared but `8.8.1-8.4.3` have appeared.
- Is there a reason why the github actions don't test exactly the same cases?
  - `8.8.1-8.4.3` doesn't seem to be tested, instead `8.4.3-8.4.3` is
  - `8.4.3` is not tested on macos.

**Comment by shayne-fletcher** [comment]
@paulbrauner-da 

> Thanks Shayne! I have two questions:
> 
> * Would you mind summarizing the changes you made to the azure config outside of the stack->cabal migration? In particular, cases like `8.8.1-8.8.1` seem to have disappeared but `8.8.1-8.4.3` have appeared.
> * Is there a reason why the github actions don't test exactly the same cases?

no, no deep reason. i'll explain further below.
   
>   * `8.8.1-8.4.3` doesn't seem to be tested, instead `8.4.3-8.4.3` is

sure. it's not 8.4.3-8.4.3 being tested (is there a label wrong somewhere?) but ghc-flavor `--da` using 8.4.3 as a build compiler. what's important here is that we test `--da` (which is 8.8.1 GHC source customized by DA. the choices for such a test are build compilers <= 8.8.1. i happened to test with build compiler 8.4.3. if you think it important (i don't) we can go back to 8.8.1 for the build compiler for this test. let me know.

>   * `8.4.3` is not tested on macos.

actually, you'll see that it is tested on macos in the azure config. what you are referring to i think is that there isn't a github action for testing it. the reason for that is github actions appear to provide aarch64 machines for macos and ghcup fails to install these older compilers (8..4.3 and 8.8.1) on that architecture. on the other hand, azure appears to provide x86_64 and that's why that test remains in azure but is absent from the github actions.

**Comment by shayne-fletcher** [comment]
@paulbrauner-da ping?

**Comment by dylant-da** [comment]
Sounds good to me, but I'll leave it to Paul - I've pinged him on DA's Slack

**Comment by basvangijzel-DA** [comment]
Hey Shayne, sorry for the delays, but we need to have a discussion with security internally to make sure changing GitHub actions, etc. is okay from their end.

**Comment by shayne-fletcher** [comment]
> Hey Shayne, sorry for the delays, but we need to have a discussion with security internally to make sure changing GitHub actions, etc. is okay from their end.

that's fine, how we resolve https://github.com/digital-asset/ghc-lib/issues/534 is independent of this PR and the one that follow. nothing in these PRs stops testing using azure resources. blocking on this issue doesn't make any sense here.

**Comment by paulbrauner-da** [comment]
Thank you for your patience @shayne-fletcher, we've now enabled GitHub actions, and I've approved the PR.

**Comment by nycnewman** [comment]
I have enabled Github Actions for this one repo

**Comment by shayne-fletcher** [comment]
> Thank you for your patience @shayne-fletcher, we've now enabled GitHub actions, and I've approved the PR.

thanks @paulbrauner-da  but please understand approving it isn't sufficient. i do not have write permission. you need to land it.

**Comment by paulbrauner-da** [comment]
> thanks @paulbrauner-da but please understand approving it isn't sufficient. i do not have write permission. you need to land it.

My bad, done.

**Comment by shayne-fletcher** [comment]
>   * `8.4.3` is not tested on macos.

@paulbrauner-da @dylant-da it looks like i've found a solution to this. there are some x86_64 runners available (https://github.com/actions/runner-images?tab=readme-ov-file#available-images). i'll circle back with a diff when the issues with the repo config that are currently blocking landing PRs are resolved.

**Pull request merged**
