### PR TITLE
Allow specifying extra CPP flags to include in generated .cabal files

### PR DESCRIPTION
**Pull request by akrmn**
ghc-lib PR: (here)
da-ghc PR: https://github.com/digital-asset/ghc/pull/123
daml PR: https://github.com/digital-asset/daml/pull/14074

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
nice thanks!

**Comment by shayne-fletcher** [comment]
i see that the hackage build is broken. i presume it relates to this PR.

```
# Running: cd ghc && git -c user.name="Cookie Monster" -c user.email=cookie.monster@seasame-street.com merge --no-edit upstream/da-master-8.8.1 upstream/da-unit-ids-8.8.1
Fast-forwarding to: upstream/da-master-8.8.1
Trying simple merge with upstream/da-unit-ids-8.8.1
Simple merge did not work, trying automatic merge.
Auto-merging compiler/basicTypes/Module.hs
ERROR: content conflict in compiler/basicTypes/Module.hs
fatal: merge program failed
Automatic merge failed; fix conflicts and then commit the result.
CI.hs: Failed when running system command: cd ghc && git -c user.name="Cookie Monster" -c user.email=cookie.monster@seasame-street.com merge --no-edit upstream/da-master-8.8.1 upstream/da-unit-ids-8.8.1
CallStack (from HasCallStack):
  error, called at src/System/Process/Extra.hs:34:9 in extra-1.6.18-B3Oo8VoU8Uo7u1ZOmQT6By:System.Process.Extra
  system_, called at CI.hs:441:30 in main:Main
```

@akrmn @cocreature

**Comment by akrmn** [comment]
Hi @shayne-fletcher, yes, I'm working on it now. The problem is that the da-unit-ids patch now creates a conflict, so I'll remove the patch and instead enable the flag `--cpp=-DDAML_PRIM` (introduced in this PR) for DA builds.

**Comment by shayne-fletcher** [comment]
> Hi @shayne-fletcher, yes, I'm working on it now. The problem is that the da-unit-ids patch now creates a conflict, so I'll remove the patch and instead enable the flag `--cpp=-DDAML_PRIM` (introduced in this PR) for DA builds.

sounds good. i'm in the process of preparing a PR for ghc-lib. with your permission i'll comment out the da build in that PR for the moment?

**Comment by shayne-fletcher** [comment]
> Hi @shayne-fletcher, yes, I'm working on it now. The problem is that the da-unit-ids patch now creates a conflict, so I'll remove the patch and instead enable the flag `--cpp=-DDAML_PRIM` (introduced in this PR) for DA builds.

sounds good. i'm in the process of preparing a PR for ghc-lib. with your permission i'll comment out the da build in that PR for the moment?

**Comment by shayne-fletcher** [comment]
or, perhaps you prefer i just leave azure alone and submit it with that build known to be broken for now?

**Comment by shayne-fletcher** [comment]
@akrmn

**Comment by akrmn** [comment]
@shayne-fletcher hm probably better to leave it alone, I'll `/azp run` when the fix is ready. Thanks!

**Pull request merged**
