### PR TITLE
failed to put this in last PR

### PR DESCRIPTION
**Pull request by shayne-fletcher**
annoyingly failed to put this line of code up in https://github.com/digital-asset/ghc-lib/pull/387. sorry.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da

**Review by garyverhaegen-da — APPROVED** [review]

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da fixed.sorry (really off my game - covid).

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da fixed.sorry (really off my game - covid).

Sorry to hear! Hope you get better soon.

**Review by garyverhaegen-da — APPROVED** [review]

**Comment by shayne-fletcher** [comment]
ok, fixed the lint. sigh. good to see CI is doing its job i suppose. moral of the story, no matter how trivial the change, run it in CI on my fork first. thanks for your patience @garyverhaegen-da

**Comment by shayne-fletcher** [comment]
> > @garyverhaegen-da fixed.sorry (really off my game - covid).
> 
> Sorry to hear! Hope you get better soon.

me too :( thank-you.

**Comment by shayne-fletcher** [comment]
ready to go @garyverhaegen-da ?

**Comment by garyverhaegen-da** [comment]
Ah sorry I lost track of this. Thanks for the nudge.

**Pull request merged**
