### PR TITLE
Add `{linux,windows,mac}-da-ghc-8.8.1-8.8.81` back to CI matrix

### PR DESCRIPTION
**Pull request by cbley-da**
related: https://github.com/digital-asset/ghc/pull/121

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]
Thanks!

**Comment by garyverhaegen-da** [comment]
@cbley-da you'll need to sign the CLA.

**Comment by shayne-fletcher** [comment]
@cbley-da @garyverhaegen-da what's happening here. looks good to land?

**Comment by garyverhaegen-da** [comment]
> @cbley-da @garyverhaegen-da what's happening here. looks good to land?

Apologies, the CLA assistant and a long weekend in Europe got in the way a bit there.

**Pull request merged**
