### PR TITLE
reuse ghc-lib-parser module definition lists in ghc-lib-test-mini-hlint

### PR DESCRIPTION
**Pull request by shayne-fletcher**
https://github.com/digital-asset/ghc-lib/pull/459 improved module selection for ghc-lib-parser. this change reuses the mechanism in ghc-lib-test-mini-hlint.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
cc @garyverhaegen-da @dylant-da @akrmn

**Review by samuel-williams-da — APPROVED** [review]
Very minor things, Thanks!

**Review by dylant-da — APPROVED** [review]
Seconding Samuel's points

**Comment by shayne-fletcher** [comment]
@samuel-williams-da @dylant-da thanks. should be good now.

**Review by samuel-williams-da — APPROVED** [review]

**Pull request merged**
