### PR TITLE
ghc-9.8.1

### PR DESCRIPTION
**Pull request by shayne-fletcher**
there is now a ghc-9.8.1 branch. this PR adds support & tests.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
cc @garyverhaegen-da @akrmn @dylant-da @samuel-williams-da

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da @dylant-da @akrmn @samuel-williams-da ping?

**Comment by garyverhaegen-da** [comment]
Hi @shayne-fletcher!

As always, thank you for all the work you put into this. Unfortunately, today is a day off for DA, so you may need to wait for Monday to get a review on this one. I apologize for the frustration this must cause.

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da @dylant-da @akrmn @samuel-williams-da how is this looking?

**Comment by dylant-da** [comment]
Hi Shayne, thanks for this! Sorry I noticed this at end of day - for some reason GitHub did not notify me. I'll get to it pronto tomorrow morning.

**Comment by shayne-fletcher** [comment]
thanks @dylant-da. i've actually got two up (another one is stacked on this one which will require rebasing after this one lands) and a third not yet published so keen to get this out of the way.

**Review by dylant-da — APPROVED** [review]

**Comment by shayne-fletcher** [comment]
@dylant-da you do know that i don't have write access and can't land this myself right?

**Pull request merged**
