### PR TITLE
support ghc-9.2.4

### PR DESCRIPTION
**Pull request by shayne-fletcher**
add a new `ghc-flavor` for ghc-9.2.4 released today.

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]

**Comment by garyverhaegen-da** [comment]
Thank you @shayne-fletcher !

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da this `/azp run` got hung up on a transient DA 8.8.1 windows build failure. might it get unblocked please (i recommend just landing as is, seen this many times before).

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da this `/azp run` got hung up on a transient DA 8.8.1 windows build failure. might it get unblocked please (i recommend just landing as is, seen this many times before)?

Sorry I'd missed that. I've restarted the job.

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da sweet. thank-you!

**Pull request merged**
