### PR TITLE
ghc-9.4.4

### PR DESCRIPTION
**Pull request by shayne-fletcher**
ghc-9.4.4 has been released. this adds support for it. incidental fixes/improvements relating to msys on windows.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
cc @garyverhaegen-da @akrmn

**Review by garyverhaegen-da — APPROVED** [review]
Thanks, and sorry for the delay!

**Comment by shayne-fletcher** [comment]
sorry @garyverhaegen-da, i just pushed a last minute change to that branch. apologies. mind restarting CI please?

**Comment by shayne-fletcher** [comment]
thanks @garyverhaegen-da . happy new year!

**Comment by garyverhaegen-da** [comment]
Happy new year to you too! Hope you had a nice break.

**Pull request merged**
