### PR TITLE
add support for ghc-9.4.1

### PR DESCRIPTION
**Pull request by shayne-fletcher**
ghc-9.4.1-alpha has been announced. add experimental support for `ghc-flavor=ghc-9.4.1`. before landing let's:
- first land https://github.com/digital-asset/ghc-lib/pull/361
- then rebase this PR on master
- then test & land this.

### CODE REVIEW

**Review by akrmn — APPROVED** [review]
This one looks good to me too :)

**Comment by shayne-fletcher** [comment]
hi @akrmn the windows failures indicate failing infra[*]. that's a shame but not related to this PR. i suggest proceeding to merge regardless. 

[*] i don't have a windows box to drill into this but in short, `stack exec pacman -S autoconf automake-wrapper make patch python tar mintty --noconfirm` has started to fail. this is a stack/ghc issue.

**Comment by shayne-fletcher** [comment]
i raised an issue for the pacman failures: https://github.com/commercialhaskell/stack/issues/5732

**Comment by shayne-fletcher** [comment]
@sofiafaro-da @akrmn can we get this attended to please?

**Comment by akrmn** [comment]
Hi @shayne-fletcher, thank you for raising the issue with stack. For now I'll try running CI again, I'd need to escalate to merge with failing CI :(

**Comment by shayne-fletcher** [comment]
> > Hi @shayne-fletcher, thank you for raising the issue with stack. For now I'll try running CI again, I'd need to escalate to merge with failing CI :(
> 
> thanks @akrmn. well, fingers crossed but i rather suspect that escalating is what we're gonna have to do for the moment :(

oh wow! it seems to be working!!

**Comment by akrmn** [comment]
🤞

**Comment by akrmn** [comment]
ah they failed :(
I'll escalate to someone who can skip PR checks

**Pull request merged**
