### PR TITLE
ghc-lib-test-mini-hlint refactor

### PR DESCRIPTION
**Pull request by shayne-fletcher**
less compact but, this refactor makes for less work when support for new flavors is added and greatly improves readability.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
@garyverhaegen-da @akrmn @dylant-da @samuel-williams-da

**Review by dylant-da — APPROVED** [review]
Refactor looks good.

For future reference: Reviewed changes excluding ghc-9.8.1 commit, because that commit is reviewed here https://github.com/digital-asset/ghc-lib/pull/472

**Comment by dylant-da** [comment]
I'm really sorry about this - approved.

**Comment by shayne-fletcher** [comment]
this landed in a squash merge of https://github.com/digital-asset/ghc-lib/pull/476 so closing

**Pull request closed without merging**
