### PR TITLE
Rm strip locs

### PR DESCRIPTION
**Pull request by shayne-fletcher**
Remove `strip-locs` example. Fixes https://github.com/digital-asset/ghc-lib/issues/306. In draft until https://github.com/digital-asset/ghc-lib/pull/305 lands at which point needs rebasing on master.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
lgtm pendng rebase, thanks!

**Comment by shayne-fletcher** [comment]
@cocreature rebased. should be good to go. can we give it another crack at an `/azp run` please?

**Comment by shayne-fletcher** [comment]
oops. ok, fixed azure i hope.

**Pull request merged**
