### PR TITLE
another little Make.hs patch for lack of semaphore_compat

### PR DESCRIPTION
**Pull request by shayne-fletcher**
- [b112546afa694efc0ae20d9d6c00b572a75c0239](https://gitlab.haskell.org/ghc/ghc/-/commit/b112546afa694efc0ae20d9d6c00b572a75c0239#1dab250036d04cfcf3530f6ff27889f723cc2dda) modifies the signature of `load'` in `GHC.Driver.Make.hs` adding a new argument `diag_wrapper`.  ignore it. 
- [fad9d092b8a81fe3661db3d18a1a02fda3dd2fe1](https://gitlab.haskell.org/ghc/ghc/-/commit/fad9d092b8a81fe3661db3d18a1a02fda3dd2fe1) causes `GHC.Driver.Session` to drop out of the list of calculated parser modules but is depended upon by `GHC.Driver.Config.Parser`. add it back.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
@akrmn @dylant-da @garyverhaegen-da

**Review by akrmn — APPROVED** [review]
LGTM, thanks @shayne-fletcher!

**Comment by shayne-fletcher** [comment]
looking good @akrmn! land please?

**Pull request merged**
